-- Tabela Fornecedor
CREATE TABLE Fornecedor (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(255) NOT NULL,
    endereco VARCHAR2(255),
    telefone VARCHAR2(50),
    PRIMARY KEY (id)
);

-- Tabela Brinquedo
CREATE TABLE Brinquedo (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(500),
    tipo VARCHAR2(100),
    classificacao VARCHAR2(50),
    tamanho NUMBER(10, 2),
    preco NUMBER(10, 2),
    fornecedor_id NUMBER, -- Relacionamento com a tabela Fornecedor
    PRIMARY KEY (id),
    FOREIGN KEY (fornecedor_id) REFERENCES Fornecedor(id)
);
